### ADD PUBLISHERS
POST http://localhost:3000/publishers
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRjMzk3NjY4ODVmMGMzNTg3Y2QxMGFhIiwic3VwZXJBZG1pbiI6dHJ1ZX0sImlhdCI6MTY5MDU0MDE1MywiZXhwIjoxNjkwNjI2NTUzfQ.TUKdc4HRBwaixy4Og-qGRuUn1NRDcj9IdW0GNp-MyRk

{
  "name": "Hilol Nashir",
  "address": "Tashkent",
  "phone": "95-555-55-00"
}

### GET PUBLISHERS
GET http://localhost:3000/publishers/?filters[is_deleted]=false
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRjM2FmMGQ1YjUzZDBjYzQyN2ZjYjg3Iiwic3VwZXJBZG1pbiI6dHJ1ZX0sImlhdCI6MTY5MDYxNDgwNSwiZXhwIjoxNjkwNzAxMjA1fQ.MLC25Zwf0E4ARlVOgqe1uMNp7ArXQbEjrR8hHKZB_b4


### GET PUBLISHER
GET http://localhost:3000/publishers/64c562933d774cb82de8f1b7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRjM2FmMGQ1YjUzZDBjYzQyN2ZjYjg3Iiwic3VwZXJBZG1pbiI6dHJ1ZX0sImlhdCI6MTY5MDYxNDgwNSwiZXhwIjoxNjkwNzAxMjA1fQ.MLC25Zwf0E4ARlVOgqe1uMNp7ArXQbEjrR8hHKZB_b4

### PATCH PUBLISHERS
PATCH http://localhost:3000/publishers/64c562933d774cb82de8f1b7
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRjMzk3NjY4ODVmMGMzNTg3Y2QxMGFhIiwic3VwZXJBZG1pbiI6dHJ1ZX0sImlhdCI6MTY5MDU0MDE1MywiZXhwIjoxNjkwNjI2NTUzfQ.TUKdc4HRBwaixy4Og-qGRuUn1NRDcj9IdW0GNp-MyRk

{
  "name": "PRINTWELL",
  "address": "Tashkent"
}


### DELETE PUBLISHERS
DELETE http://localhost:3000/publishers/64c3f70a98403fb12b4b1dc2
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRjMzk3NjY4ODVmMGMzNTg3Y2QxMGFhIiwic3VwZXJBZG1pbiI6dHJ1ZX0sImlhdCI6MTY5MDU0MDE1MywiZXhwIjoxNjkwNjI2NTUzfQ.TUKdc4HRBwaixy4Og-qGRuUn1NRDcj9IdW0GNp-MyRk
